### PR TITLE
Context path improvement

### PR DESCRIPTION
**Pull request by btargac**
Added contextPath for eureka config servers that may require contexPath.

### CODE REVIEW

**Comment by victorherraiz** [comment]
Thank you for you pull request.

Did you try to include the context path in the endpoint value? 
`endpoint: "http://localhost:8888/contextpath"`

**Comment by btargac** [comment]
Hi @victorherraiz  I tried that solution but it didn't work, so I thought that HTTP request should have the '/contextPath' within the path value, where it is constructed at getPath function.

**Comment by victorherraiz** [comment]
Thank you again. Therefore, there is a bug that needs some work.... I will include your pull request in the next release. I hope I will have some time tomorrow evening  🍻

**Comment by victorherraiz** [comment]
I just resolved the bug. Endpoints now supports context path v0.3.1. Thanks for the feedback

**Comment by victorherraiz** [comment]
The context path could be specified in the endpoint

**Pull request closed without merging**
